name: scribble_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.5.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  objectbox: ^2.5.0
  objectbox_flutter_libs: ^2.5.0
  path_provider: ^2.1.2
  archive: ^3.6.1
  auto_size_text: 3.0.0
  collection: 1.18.0
  equatable: 2.0.5
  flutter_blue_plus: ^1.32.7
  font_awesome_flutter: 10.6.0
  from_css_color: 2.0.0
  http: ^1.2.1
  intl: ^0.19.0
  mime_type: 1.0.0
  page_transition: 2.1.0
  pdf: ^3.11.0
  permission_handler: ^11.3.1
  share_plus: ^9.0.0
  shared_preferences: ^2.2.3
  smooth_page_indicator: 1.1.0
  url_launcher: ^6.3.0
  url_launcher_platform_interface: 2.3.2
  wav: ^1.3.0
  lottie: ^3.1.2
  flutter_tilt: any
  path: ^1.9.0
  uuid: ^4.4.0
  tuple: ^2.0.2
  googleapis_auth: ^1.6.0
  envied: ^0.5.4+1
  mime: ^1.0.5
  instabug_flutter: ^13.0.0
  instabug_http_client: ^2.4.0
  mixpanel_flutter: ^2.2.0
  expandable_text: ^2.3.0
  flutter_native_splash: ^2.4.0
  flutter_svg: ^2.0.10+1
  gradient_borders: ^1.0.1
  nordic_dfu: ^6.1.4+hotfix
  package_info_plus: ^8.0.1
  ml_linalg: any
  flutter_foreground_task: ^8.2.0
  deepgram_speech_to_text: ^2.1.1
  upgrader: ^10.3.0
  crypto: ^3.0.3
  encrypt: ^5.0.3
  flutter_markdown: ^0.7.2+1
  file_picker: ^8.0.5
  record: ^5.1.2
  onesignal_flutter: ^5.1.2
  flutter_background_service: ^5.0.7
  growthbook_sdk_flutter: ^3.9.2
  flutter_rating_bar: ^4.0.1
  device_calendar: ^4.3.2
  flutter_timezone: ^2.0.0
  sign_in_button: ^3.2.0
  sign_in_with_apple: ^6.1.1
  google_sign_in: ^6.2.1
  location: ^7.0.0
  cached_network_image: ^3.3.1
  map_launcher: ^3.3.1
  internet_connection_checker_plus: ^2.5.0
  docx_template: ^0.4.0
  enum_to_string: ^2.0.1
  visibility_detector: ^0.4.0+2
  version: ^3.0.2
  webview_flutter: ^4.8.0
  flutter_sound: ^9.10.0
  flutter_blue: ^0.8.0
  audioplayers: ^6.1.0
  just_audio: ^0.9.24


dependency_overrides:
  http: ^1.2.1
  uuid: ^4.4.0
  js: ^0.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.8
  objectbox_generator: ^2.5.0
  flutter_launcher_icons: 0.13.1
  image: ^4.2.0
  integration_test:
    sdk: flutter
  lints: ^4.0.0
  envied_generator: ^0.5.4+1
  flutter_flavorizr: ^2.2.3

flutter:

  uses-material-design: true

  assets:
    - assets/

macos:
  entitlements_path: macos/Runner/Release.entitlements